dist: xenial
language: php

services:
  - mysql

env:
  - PDNS_VERSION=41
  - PDNS_VERSION=42

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mysql -e 'CREATE DATABASE powerdns;'
  - if [[ "$PDNS_VERSION" == "41" ]]; then mysql -u root powerdns < .travis/pdns-41.sql; fi
  - if [[ "$PDNS_VERSION" == "42" ]]; then mysql -u root powerdns < .travis/pdns-42.sql; fi

install:
  - ./.travis/install-pdns.sh
  - composer install

